# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Hugo setup
        # You may pin to the exact commit or the version.
        # uses: peaceiris/actions-hugo@2e89aa66d0093e4cd14751b3028fc1a179452c2e
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          hugo-version: latest
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true
      
      - name: Build Site
        run: hugo

      - name: Algolia Uploader
        # You may pin to the exact commit or the version.
        # uses: wangchucheng/algolia-uploader@2146c50bde2441041f9727c2b89accebcc998c74
        uses: wangchucheng/algolia-uploader@v0.1.0
        with:
          # Application ID of Algolia
          app_id: PCYQIIOQHO
          # Admin API Key of Algolia
          admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          # Index name of Algolia
          index_name: index.json
          # Index file path
          index_file_path: public/

